In [94]:
import geopandas as gpd
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np

In [95]:
df = gpd.read_file("pop_dens_bigger_20.geojson")

In [96]:
df.columns

Index(['ID_1', 'NAME_1', 'ID_2', 'NAME_2', 'ID_3', 'NAME_3', 'HASC_3',
       'TYPE_3', 'SHAPE_LENG', 'SHAPE_AREA', 'CC_3', 'cc3int', 'sc_mean',
       '_stdev', 'geometry'],
      dtype='object')

In [97]:
df

,ID_1,NAME_1,ID_2,NAME_2,ID_3,NAME_3,HASC_3,TYPE_3,SHAPE_LENG,SHAPE_AREA,CC_3,cc3int,sc_mean,_stdev,geometry
0,70,Elbasan,502,Librazhdit,642,Perrenjas,AL.EB.LB.PE,Bashkia,0.238663,0.002288,70502642,70502642,1.0,26.122339,"MULTIPOLYGON (((20.53112 41.02797, 20.52811 41..."
1,70,Elbasan,502,Librazhdit,643,Polis,AL.EB.LB.PL,Commune,0.447364,0.008551,70502643,70502643,1.0,6.487566,"MULTIPOLYGON (((20.24295 41.19254, 20.24405 41..."
2,70,Elbasan,502,Librazhdit,644,Qendër,AL.EB.LB.QE,Bashkia,1.086516,0.018836,70502644,70502644,1.0,37.631018,"MULTIPOLYGON (((20.44642 41.26683, 20.45071 41..."
3,70,Elbasan,502,Librazhdit,645,Qukës,AL.EB.LB.QU,Commune,0.597366,0.013284,70502645,70502645,1.0,12.227250,"MULTIPOLYGON (((20.53380 41.15680, 20.53371 41..."
4,70,Elbasan,502,Librazhdit,646,Rrajcë,AL.EB.LB.RJ,Commune,0.513769,0.007224,70502646,70502646,1.0,12.257411,"MULTIPOLYGON (((20.59682 41.13321, 20.59858 41..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,78,Vlorë,528,Vlorës,901,Selenicë,AL.VR.VL.SL,Bashkia,0.152191,0.001186,78528901,78528901,1.0,11.677516,"MULTIPOLYGON (((19.62640 40.55484, 19.62869 40..."
374,78,Vlorë,528,Vlorës,902,Sevaster,AL.VR.VL.SV,Commune,0.484879,0.009255,78528902,78528902,0.0,0.851441,"MULTIPOLYGON (((19.73766 40.43615, 19.73858 40..."
375,78,Vlorë,528,Vlorës,903,Shushicë,AL.VR.VL.SH,Commune,0.360155,0.004100,78528903,78528903,1.0,3.797126,"MULTIPOLYGON (((19.56176 40.52774, 19.56384 40..."
376,78,Vlorë,528,Vlorës,904,Vllahinë,AL.VR.VL.VH,Commune,0.696071,0.011943,78528904,78528904,0.0,2.575048,"MULTIPOLYGON (((19.61829 40.49855, 19.61974 40..."
377,78,Vlorë,528,Vlorës,905,Vlorë,AL.VR.VL.VR,Bashkia,0.275402,0.002078,78528905,78528905,1.0,551.659903,"MULTIPOLYGON (((19.49991 40.48431, 19.50321 40..."

In [98]:
df = df[df.sc_mean != 1]

In [99]:
df

,ID_1,NAME_1,ID_2,NAME_2,ID_3,NAME_3,HASC_3,TYPE_3,SHAPE_LENG,SHAPE_AREA,CC_3,cc3int,sc_mean,_stdev,geometry
5,70,Elbasan,502,Librazhdit,647,Stravaj,AL.EB.LB.SV,Commune,0.665457,0.012819,70502647,70502647,0.0,3.125038,"MULTIPOLYGON (((20.34156 41.08719, 20.34566 41..."
17,72,Gjirokastër,507,Gjirokastrës,704,Odrie,AL.GK.GJ.OD,Commune,0.264483,0.003655,72507704,72507704,0.0,0.871837,"MULTIPOLYGON (((20.12957 40.21584, 20.13114 40..."
18,72,Gjirokastër,507,Gjirokastrës,705,Picar,AL.GK.GJ.PC,Commune,0.576583,0.012091,72507705,72507705,0.0,0.516347,"MULTIPOLYGON (((20.07063 40.21799, 20.07007 40..."
19,72,Gjirokastër,507,Gjirokastrës,706,Pogon,AL.GK.GJ.PG,Commune,0.672195,0.020535,72507706,72507706,0.0,1.470320,"MULTIPOLYGON (((20.41577 40.11908, 20.41696 40..."
20,72,Gjirokastër,507,Gjirokastrës,707,Qen.Liboh,None,Bashkia,0.696288,0.006599,72507707,72507707,0.0,6.134415,"MULTIPOLYGON (((20.27113 40.10175, 20.27774 40..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,78,Vlorë,528,Vlorës,896,Hore Vranisht,AL.VR.VL.HV,Commune,0.875855,0.024515,78528896,78528896,0.0,0.786822,"MULTIPOLYGON (((19.81940 40.27306, 19.82490 40..."
369,78,Vlorë,528,Vlorës,897,Kotë,AL.VR.VL.KT,Commune,0.723424,0.013676,78528897,78528897,0.0,3.953840,"MULTIPOLYGON (((19.57215 40.45898, 19.57561 40..."
371,78,Vlorë,528,Vlorës,899,Orikum,AL.VR.VL.OR,Bashkia,1.472619,0.035694,78528899,78528899,0.0,99.923510,"MULTIPOLYGON (((19.32068 40.43909, 19.32069 40..."
374,78,Vlorë,528,Vlorës,902,Sevaster,AL.VR.VL.SV,Commune,0.484879,0.009255,78528902,78528902,0.0,0.851441,"MULTIPOLYGON (((19.73766 40.43615, 19.73858 40..."
376,78,Vlorë,528,Vlorës,904,Vllahinë,AL.VR.VL.VH,Commune,0.696071,0.011943,78528904,78528904,0.0,2.575048,"MULTIPOLYGON (((19.61829 40.49855, 19.61974 40..."

In [65]:
# df2 = df["sc_mean"].replace(df["sc_mean"]<25, 0)

df['sc_mean'].values[df['sc_mean'].values > 30] = 1
df['sc_mean'].values[df['sc_mean'].values != 1] = 0

In [59]:
df['sc_mean'].values[df['sc_mean'].values == 1] = None

In [ ]:
df['sc_mean']

In [83]:
df.to_file("alb2_rwi_1_0mean.geojson", driver='GeoJSON')

In [19]:
scaler = StandardScaler()
scaler2 = MinMaxScaler()
t = np.asarray(df["sc_mean"])
t3 = np.asarray(df["_median"])
t = t.reshape(-1,1)
t3 = t.reshape(-1,1)
arr = scaler.fit_transform(t)
arr2 = scaler2.fit_transform(t)
arr3 = scaler2.fit_transform(t3)
df["sc_mean"] = arr2
df["sc_mean_std2"] = arr
df["_median"] = arr3

In [20]:
df[['NAME_1', 'NAME_2', 'NAME_3', 'sc_mean', '_median', '_stdev']].describe()

          sc_mean     _median      _stdev
count  378.000000  378.000000  378.000000
mean     0.630555    0.630555    0.054633
std      0.167099    0.167099    0.023042
min      0.000000    0.000000    0.017259
25%      0.547088    0.547088    0.037793
50%      0.646710    0.646710    0.050325
75%      0.757470    0.757470    0.065752
max      1.000000    1.000000    0.145698

In [82]:
# invert sc mean from low to high

df["sc_mean"] = 1 - df["sc_mean"]
# df["_median"] = 1 - df["_median"]

In [24]:
df[['NAME_1', 'NAME_2', 'NAME_3', 'sc_mean', '_median', '_stdev']].describe()

            sc_mean       _median      _stdev
count  3.780000e+02  3.780000e+02  378.000000
mean   3.694455e-01  3.694455e-01    0.054633
std    1.670993e-01  1.670993e-01    0.023042
min    1.110223e-16  1.110223e-16    0.017259
25%    2.425301e-01  2.425301e-01    0.037793
50%    3.532902e-01  3.532902e-01    0.050325
75%    4.529118e-01  4.529118e-01    0.065752
max    1.000000e+00  1.000000e+00    0.145698

In [100]:
df.to_file("mask.geojson", driver='GeoJSON')

In [60]:
# df2 = pd.read_csv("Data_Alb_cov_for_tool.csv")
# df2.replace(-9999,0,inplace = True)

In [61]:
# data_minmax = MinMaxScaler().fit_transform(df2)
# data_minmax = pd.DataFrame(data_minmax,
#                            index=df2.index,
#                            columns=df2.columns)

In [63]:
# data_minmax.to_csv("Data_Alb_cov_for_tool_fixed.csv")